// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcO0zZznYNlc0hgDa0JZqWqgLIhFau_uM',
    appId: '1:826609161292:web:411145bf9b7766981150e9',
    messagingSenderId: '826609161292',
    projectId: 'whiskr-121bd',
    authDomain: 'whiskr-121bd.firebaseapp.com',
    storageBucket: 'whiskr-121bd.firebasestorage.app',
    measurementId: 'G-7P2PBWV1YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSkGFkkm9cCUtMjitZDyC24C1263p1Ftg',
    appId: '1:826609161292:android:f9b11efbaa4f68f41150e9',
    messagingSenderId: '826609161292',
    projectId: 'whiskr-121bd',
    storageBucket: 'whiskr-121bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCcGNSdhDDL3MAwSG4_L3Js-9ffi_rBgI',
    appId: '1:826609161292:ios:72c9417bc45f1f581150e9',
    messagingSenderId: '826609161292',
    projectId: 'whiskr-121bd',
    storageBucket: 'whiskr-121bd.firebasestorage.app',
    iosBundleId: 'com.example.whiskr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCcGNSdhDDL3MAwSG4_L3Js-9ffi_rBgI',
    appId: '1:826609161292:ios:72c9417bc45f1f581150e9',
    messagingSenderId: '826609161292',
    projectId: 'whiskr-121bd',
    storageBucket: 'whiskr-121bd.firebasestorage.app',
    iosBundleId: 'com.example.whiskr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcO0zZznYNlc0hgDa0JZqWqgLIhFau_uM',
    appId: '1:826609161292:web:6e6ae8b26e890bca1150e9',
    messagingSenderId: '826609161292',
    projectId: 'whiskr-121bd',
    authDomain: 'whiskr-121bd.firebaseapp.com',
    storageBucket: 'whiskr-121bd.firebasestorage.app',
    measurementId: 'G-P7V4TF9C25',
  );
}
